import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "node:fs";
import path from "node:path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const vaultPath = process.env.OBSIDIAN_VAULT_PATH ?? "C:\\Obsidian\\Dev";
const outDir = path.join(
  vaultPath,
  ".obsidian",
  "plugins",
  "obsidian-diff-history"
);

if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

const copyStaticFiles = {
  name: "copy-static-files",
  setup(build) {
    build.onEnd(() => {
      try {
        fs.copyFileSync("manifest.json", path.join(outDir, "manifest.json"));

        const cssFile = "src/styles.css";
        if (fs.existsSync(cssFile)) {
          fs.copyFileSync(cssFile, path.join(outDir, "styles.css"));
        }

        console.log("Built to " + outDir);
      } catch (e) {
        console.error("Failed to copy static files:", e);
      }
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  platform: "browser",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(outDir, "main.js"),
  plugins: [copyStaticFiles],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
